version: "3.9"

services:
 postgres:
  image: postgres
  ports: 
    - "5432:5432"
  volumes:
    - persist:/var/lib/postgresql/data
  volumes: 
    - ./.env:/app/.env
  environment:
    - POSTGRES_DB=mailauth
    - POSTGRES_USER=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
 
 application:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  volumes:
    - type: bind
      source: .env  
      target: /app/.env
  ports:
    - "3000:3000"
  links:
    - postgres 
  depends_on:
    - postgres
 
 application-test:
  build:
    context: .
    dockerfile: Dockerfile
    target: test 
  volumes: 
    - ./.env:/app/.env
  links:
    - postgres
  depends_on:
    - postgres 

volumes:
  persist:
