version: "3.9"

services:
 postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - persist:/var/lib/postgresql/data
    - ./.env:/app/.env
  environment:
    - POSTGRES_DB=mailauth
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root

 application:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  volumes:
    - ./.env:/app/.env
  environment:
    - DB_HOST=postgres
  ports:
    - "3000:3000"
  links:
    - postgres
  depends_on:
    - postgres
  command:
     [
       "./wait-for-it/wait-for-it.sh",
       "postgres:5432",
       "--",
       "npm",
       "run",
       "start",
     ]

 test:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  volumes:
    - ./.env:/app/.env
  environment:
    - DB_HOST=postgres
  ports:
    - "3000:3000"
  links:
    - postgres
  depends_on:
    - postgres
  command:
     [
       "./wait-for-it/wait-for-it.sh",
       "postgres:5432",
       "--",
       "npm",
       "run",
       "test:coverage",
     ]

 migrate:
   build:
     context: .
   volumes:
   - ./.env:/app/.env
   command:
     [
       "./wait-for-it/wait-for-it.sh",
       "postgres:5432",
       "--",
       "npm",
       "run",
       "migrate",
     ]
   links:
     - postgres
   depends_on:
     - postgres
   env_file: ./.env
   environment:
     - DB_HOST=postgres


volumes:
  persist:
