version: "3.9"

services:
 postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - persist:/var/lib/postgresql/data
    - env_file:./.env
  environment:
    - POSTGRES_DB=mailauth
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root
  healthcheck:
    test: ['CMD-SHELL', 'pg_isready']
    interval: 3s
    timeout: 5s
    retries: 5


 application:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  environment:
    - DB_HOST=postgres
  ports:
    - "3000:3000"
  links:
    - postgres
  depends_on:
    postgres:
      condition: service_healthy
  command:
     [
       "npm",
       "run",
       "start",
     ]

 test:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  environment:
    - DB_HOST=postgres
  links:
    - postgres
  depends_on:
    postgres:
      condition: service_healthy
  command:
     [
       "npm",
       "run",
       "test:coverage",
     ]

 migrate:
   build:
     context: .
   command:
     [
       "npm",
       "run",
       "migrate",
     ]
   links:
     - postgres
   depends_on:
     postgres:
       condition: service_healthy
   environment:
     - DB_HOST=postgres


volumes:
  persist:
