version: "3.9"

services:
 db:
  image: postgres
  volumes:
    - persist:/var/lib/postgresql/data
  volumes: 
    - ./.env:/app/.env
  environment:
    - POSTGRES_DB=mailauth
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_HOST_AUTH_METHOD=trust
 
 application:
  build:
    context: .
    dockerfile: Dockerfile
    target: app
  volumes: 
    - ./.env:/app/.env
  ports:
    - "3001:3001"
  links:
    - "db:database"
  depends_on:
    - db
 
 application-test:
  build:
    context: .
    dockerfile: Dockerfile
    target: test 
  volumes: 
    - ./.env:/app/.env
  depends_on:
    - db

volumes:
  persist:
