name: Node.js CI

on:
  push:
    branches: [ typescript ]
  pull_request:
    branches: [ typescript ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: make images 
        run: docker-compose up 

      - name: migration
        run: docker-compose run migrate
  
      - name: test
        run: docker-compose run test


