name: Node.js CI

on:
  push:
    branches: [ typescript ]
  pull_request:
    branches: [ typescript ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: make migration image 
        run: docker-compose build migrate

      - name: make test image  
        run: docker-compose build test 
  
      - name: test
        run: docker-compose run test


